modLoader="javafml"
loaderVersion="[47,)"                      # Forge 47+ (MC 1.20.1)
license="MIT"

[[mods]]
modId="combatflask"
version="1.0.0"
displayName="Combat Flask Mod"
authors="TonNom"
description='''Adds elemental combat flasks (Fire, Frost, Storm).'''

# Forge
[[dependencies.combatflask]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

# Minecraft
[[dependencies.combatflask]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

# Iron's Spells 'n Spellbooks
[[dependencies.combatflask]]
modId="irons_spellbooks"
mandatory=true
versionRange="[1.20.1-3.4.0.11,1.20.1-4.0.0)"
ordering="NONE"
side="BOTH"
